CREATE DATABASE JAVACRUD;

USE JAVACRUD;

CREATE TABLE UserTable (
    Id_User INT PRIMARY KEY AUTO_INCREMENT,
    Name_User VARCHAR(50) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    Email_User VARCHAR(50) NOT NULL UNIQUE,
    Number_User CHAR(11) NOT NULL UNIQUE
)